.TH NDSFUSE 1 "2010 June 30" "0.3"
.SH NAME
ndsfuse - A tool to mount NDS ROMs using FUSE.

.SH SYNOPSIS
.B ndsfuse
[rom.nds] [mount_point] [fuse_options]

.SH DESCRIPTION
.P
(Taken from https://web.archive.org/web/20100924063114/https://someh4x0r.wordpress.com/2010/09/15/ndsfuse/)
.P
This is  a program that is similar to wiifuse. It allows mounting .nds files using FUSE.

.SH OPTIONS
See fuse (1) options section.

.SH AUTHORS
Originally written by Someh4x0r. Revisions by Andrew Ekstedt and fm'latghor <fm@fmlatghor.com>.

.SH COPYRIGHT
Copyright \(co 2021 Someh4x0r. All Rights Reserved.

.SH SEE ALSO
.BR fuse (1)
